### ISSUE TITLE
Cannot run the project on my computer

### ISSUE THREAD

**Issue by HerschaLo** [GDSCUTM-CommunityProjects/schedulr#14]
Hello,

I was hoping to contribute to this project, but when I tried to run the Django API server on my computer to test it, it said I didn't have the secret key required to run it. I would appreciate it if you could provide me the secret key so that I can try testing the app for myself during development. My discord handle is HerschaLo#4613. 

Thanks,

Stephen Le

**Comment by r4z33n4l1** [comment]
> Hello,
> 
> I was hoping to contribute to this project, but when I tried to run the Django API server on my computer to test it, it said I didn't have the secret key required to run it. I would appreciate it if you could provide me the secret key so that I can try testing the app for myself during development. My discord handle is HerschaLo#4613.
> 
> Thanks,
> 
> Stephen Le

Hey add me on discord, r4z33n#9710 . I can help you get it set up!
